
coverage_service: cobertura_xml
xcodeproj: ./MoodJourney.xcodeproj
scheme: MoodJourney
ignore:
 - MoodJourney/Features/Home/Presentation/*
 - MoodJourney/Features/Splash/Presentation/*
 - MoodJourney/Features/Sign in/Presentation/*
 - MoodJourney/Features/Feeling/Presentation/*
 - MoodJourney/Features/Activity/Presentation/*
 - MoodJourney/Features/Cheerleaders/Presentation/*
 - MoodJourney/Features/Reaction/Presentation/*
 - MoodJourney/Core/DI/*
 - MoodJourney/Core/Coordinator/*
 - MoodJourney/Core/Tabbar/*
 - MoodJourney/Core/Type/*
 - MoodJourney/Core/Manager/*
 - MoodJourneyTests/*
 - MoodJourney/MoodJourneyApp.swift
