
coverage_service: cobertura_xml
xcodeproj: ./MoodJourney.xcodeproj
scheme: MoodJourney
ignore:
 - MoodJourney/Features/Home/Presentation/*
 - MoodJourney/Features/Splash/Presentation/*
 - MoodJourney/Features/Feeling/Presentation/*
 - MoodJourney/Features/Activity/Presentation/*
 - MoodJourney/Features/Cheerleaders/Presentation/*
 
