# .circleci/config.yml
version: 2.1
orbs:
  codecov: codecov/codecov@3.2.4

jobs:
  build-and-test:
    macos:
      xcode: 14.2.0
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: test
    steps:
      - checkout
      - run: bundle install
      - run: brew install swiftlint
      - run:
          name: Fastlane
          command: bundle exec fastlane $FASTLANE_LANE
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan
      - run: bundle exec slather
      - codecov/upload


workflows:
  build-test-adhoc:
    jobs:
      - build-and-test
  