version: 2
jobs:
build-and-test:
macos:
xcode: "10.2.1"
environment:
FL_OUTPUT_DIR: output
steps:
- checkout
run:
name: Build and run tests
command: fastlane scan environment:
SCAN_DEVICE: iPhone 8 SCAN_SCHEME: Larg
- store_test_results: path: output/scan
- store_artifacts: path: output
workflows:
version: 2
build-and-test:
jobs:
- build-and-test
