//
//  MoodJourneyTests-MoodJourneyMocks.generated.swift
//  MoodJourney
//
//  Generated by Mockingbird v0.20.0.
//  DO NOT EDIT
//

@testable import Mockingbird
@testable import MoodJourney
import Foundation
import Swift
import SwiftUI

// No mocks used in 'MoodJourneyTests'. Mockingbird is configured to only generate mocks for types
// that are explicitly initialized in your tests with `mock(SomeType.self)`. For more information,
// see 'Thunk Pruning' in the README.
