# fastlane/Fastfile
default_platform :ios

platform :ios do
  before_all do
    setup_circle_ci
  end

  desc "Runs all the tests"
  lane :test do
    scan(include_simulator_logs: false)
    swiftlint(
       mode: :lint,
       quiet: true,
       config_file: ".swiftlint-ci.yml",
       strict: false)
  end

end